name: Auto Cherry-Pick to Branch

on:
  pull_request:
    types:
      - closed
    branches:
      - master
permissions:
  checks: write
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  auto_cherry_pick:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dev/3.0.x') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install PyGithub

      - name: Auto cherry-pick
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.repository }}
          CONFLICT_LABEL: cherry-pick-conflict-in-3.0
        run: |
          python tools/auto-pick-script.py ${{ github.event.pull_request.number }} branch-3.0  
